spring: 
  cloud: 
    config: 
      name: microservicecloud-config-eureka-client     #需要从github上读取的资源名称，注意没有yml后缀名
      profile: dev #读取资源的环境
      label: master 
      uri: http://config-3344.com:3344      #获取资源的地址

